export const classify = [
  {
    id: 1,
    value: "数码",
    children: [
      [
        { id: 1.11, value: "充电宝" },
        { id: 1.12, value: "风扇" },
        { id: 1.13, value: "手机" },
        { id: 1.14, value: "空调" },
        { id: 1.15, value: "冰箱" },
        { id: 1.16, value: "华为" },
        { id: 1.17, value: "笔记本" },
        { id: 1.18, value: "键盘" },
      ],
      [
        { id: 1.21, value: "充电宝" },
        { id: 1.22, value: "风扇" },
        { id: 1.23, value: "手机" },
        { id: 1.24, value: "空调" },
        { id: 1.25, value: "冰箱" },
        { id: 1.26, value: "华为" },
        { id: 1.27, value: "笔记本" },
        { id: 1.28, value: "键盘" },
      ],
      [
        { id: 1.31, value: "充电宝" },
        { id: 1.32, value: "风扇" },
        { id: 1.33, value: "手机" },
        { id: 1.34, value: "空调" },
        { id: 1.35, value: "冰箱" },
        { id: 1.36, value: "华为" },
        { id: 1.37, value: "笔记本" },
        { id: 1.38, value: "键盘" },
      ],
      [
        { id: 1.41, value: "充电宝" },
        { id: 1.42, value: "风扇" },
        { id: 1.43, value: "手机" },
        { id: 1.44, value: "空调" },
        { id: 1.45, value: "冰箱" },
        { id: 1.46, value: "华为" },
        { id: 1.47, value: "笔记本" },
        { id: 1.48, value: "键盘" },
      ],
    ],
  },
  {
    id: 2,
    value: "数码",
    children: [
      [
        { id: 1.11, value: "充电宝" },
        { id: 1.12, value: "风扇" },
        { id: 1.13, value: "手机" },
        { id: 1.14, value: "空调" },
        { id: 1.15, value: "冰箱" },
        { id: 1.16, value: "华为" },
        { id: 1.17, value: "笔记本" },
        { id: 1.18, value: "键盘" },
      ],
      [
        { id: 1.21, value: "充电宝" },
        { id: 1.22, value: "风扇" },
        { id: 1.23, value: "手机" },
        { id: 1.24, value: "空调" },
        { id: 1.25, value: "冰箱" },
        { id: 1.26, value: "华为" },
        { id: 1.27, value: "笔记本" },
        { id: 1.28, value: "键盘" },
      ],
      [
        { id: 1.31, value: "充电宝" },
        { id: 1.32, value: "风扇" },
        { id: 1.33, value: "手机" },
        { id: 1.34, value: "空调" },
        { id: 1.35, value: "冰箱" },
        { id: 1.36, value: "华为" },
        { id: 1.37, value: "笔记本" },
        { id: 1.38, value: "键盘" },
      ],
      [
        { id: 1.41, value: "充电宝" },
        { id: 1.42, value: "风扇" },
        { id: 1.43, value: "手机" },
        { id: 1.44, value: "空调" },
        { id: 1.45, value: "冰箱" },
        { id: 1.46, value: "华为" },
        { id: 1.47, value: "笔记本" },
        { id: 1.48, value: "键盘" },
      ],
    ],
  },
  {
    id: 3,
    value: "数码",
    children: [
      [
        { id: 1.11, value: "充电宝" },
        { id: 1.12, value: "风扇" },
        { id: 1.13, value: "手机" },
        { id: 1.14, value: "空调" },
        { id: 1.15, value: "冰箱" },
        { id: 1.16, value: "华为" },
        { id: 1.17, value: "笔记本" },
        { id: 1.18, value: "键盘" },
      ],
      [
        { id: 1.21, value: "充电宝" },
        { id: 1.22, value: "风扇" },
        { id: 1.23, value: "手机" },
        { id: 1.24, value: "空调" },
        { id: 1.25, value: "冰箱" },
        { id: 1.26, value: "华为" },
        { id: 1.27, value: "笔记本" },
        { id: 1.28, value: "键盘" },
      ],
      [
        { id: 1.31, value: "充电宝" },
        { id: 1.32, value: "风扇" },
        { id: 1.33, value: "手机" },
        { id: 1.34, value: "空调" },
        { id: 1.35, value: "冰箱" },
        { id: 1.36, value: "华为" },
        { id: 1.37, value: "笔记本" },
        { id: 1.38, value: "键盘" },
      ],
      [
        { id: 1.41, value: "充电宝" },
        { id: 1.42, value: "风扇" },
        { id: 1.43, value: "手机" },
        { id: 1.44, value: "空调" },
        { id: 1.45, value: "冰箱" },
        { id: 1.46, value: "华为" },
        { id: 1.47, value: "笔记本" },
        { id: 1.48, value: "键盘" },
      ],
    ],
  },
  {
    id: 4,
    value: "数码",
    children: [
      [
        { id: 1.11, value: "充电宝" },
        { id: 1.12, value: "风扇" },
        { id: 1.13, value: "手机" },
        { id: 1.14, value: "空调" },
        { id: 1.15, value: "冰箱" },
        { id: 1.16, value: "华为" },
        { id: 1.17, value: "笔记本" },
        { id: 1.18, value: "键盘" },
      ],
      [
        { id: 1.21, value: "充电宝" },
        { id: 1.22, value: "风扇" },
        { id: 1.23, value: "手机" },
        { id: 1.24, value: "空调" },
        { id: 1.25, value: "冰箱" },
        { id: 1.26, value: "华为" },
        { id: 1.27, value: "笔记本" },
        { id: 1.28, value: "键盘" },
      ],
      [
        { id: 1.31, value: "充电宝" },
        { id: 1.32, value: "风扇" },
        { id: 1.33, value: "手机" },
        { id: 1.34, value: "空调" },
        { id: 1.35, value: "冰箱" },
        { id: 1.36, value: "华为" },
        { id: 1.37, value: "笔记本" },
        { id: 1.38, value: "键盘" },
      ],
      [
        { id: 1.41, value: "充电宝" },
        { id: 1.42, value: "风扇" },
        { id: 1.43, value: "手机" },
        { id: 1.44, value: "空调" },
        { id: 1.45, value: "冰箱" },
        { id: 1.46, value: "华为" },
        { id: 1.47, value: "笔记本" },
        { id: 1.48, value: "键盘" },
      ],
    ],
  },
];
